name: cybics_game
description: "Cybics Game built with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/menu.mp3
    - assets/level1.mp3
    - assets/level2.mp3
    - assets/level3.mp3
    - assets/death.mp3
    - assets/god.mp3
